services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: klokk-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://0.0.0.0:8080/api/health"]
      interval: 5s
      timeout: 5s
      retries: 3